version: '3.3'
services:
  web:
    container_name: tubes-1
    user: "1000:1000"
    build: 
        context: .
        dockerfile: Dockerfile
    # image: tubes-1:latest
    ports:
      - 8000:80
    depends_on:
      - db
    volumes: 
      - ./app:/var/www/html/
      - ./db/data_seeding:/var/www/html/seed
    networks:
      - wbd-network
  db:
    container_name: wbd-db
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'wbd-db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - '9096:3306'
    expose:
      - '3306'
    networks:
      - wbd-network
networks:
  wbd-network: