version: '3.3'
services:
  web:
    build: 
        context: .
        dockerfile: Dockerfile
    image: tubes-1:latest
    ports:
      - 8000:80
    depends_on:
      - db
    volumes: 
      - ./src/app:/var/www/html/
  db:
    container_name: wbd-db
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'wbd-db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - '9096:3306'
    expose:
    - '9096'